import{a as q,S as P,i}from"./assets/vendor-CrlV4O_2.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const a of r.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&n(a)}).observe(document,{childList:!0,subtree:!0});function o(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function n(e){if(e.ep)return;e.ep=!0;const r=o(e);fetch(e.href,r)}})();const j="43795533-00e69c3734dde476e8d836fd2",M="https://pixabay.com/api/",p=async(s,t)=>(await q.get(M,{params:{key:j,q:s,orientation:"horizontal",safesearch:!0,page:t,per_page:15}})).data,g=document.querySelector(".js-search-list"),f=document.querySelector(".js-loader"),y=document.querySelector(".js-search-more"),$=new P(".gallery-link",{captionsData:"alt",captionDelay:250}),L=s=>{const t=s.map(({webformatURL:o,largeImageURL:n,tags:e,likes:r,views:a,comments:w,downloads:b})=>`<li class="search-list-item">
                    <a class="gallery-link" href="${n}">
                      <img class="search-list-img" src="${o}" alt="${e}" />
                    </a>
                    <ul>
                      <li><h3>Likes</h3><p>${r}</p></li>
                      <li><h3>Views</h3><p>${a}</p></li>
                      <li><h3>Comments</h3><p>${w}</p></li>
                      <li><h3>Downloads</h3><p>${b}</p></li>
                    </ul>
                  </li>`).join("");g.insertAdjacentHTML("beforeend",t),$.refresh()},B=()=>{g.innerHTML=""},R=()=>{f.classList.add("is-active")},h=()=>{f.classList.remove("is-active")},v=()=>{y.classList.add("is-active")},S=()=>{y.classList.remove("is-active")},u=document.querySelector(".js-search-form"),E=document.querySelector(".js-search-list"),m=document.querySelector(".js-loader-more"),O=document.querySelector(".js-search-more");let c=1,l="",d=0;u.addEventListener("submit",async s=>{if(s.preventDefault(),l=u.elements.enterForSearsh.value.trim(),!l){i.warning({position:"topRight",message:"Please enter a search term."});return}c=1,B(),S(),R();try{const t=await p(l,c);if(d=t.totalHits,!d){h(),i.error({position:"topRight",message:"Sorry, there are no images matching your search query. Please try again!"}),u.reset();return}L(t.hits),h(),d>15?v():i.info({position:"topRight",message:"We're sorry, but you've reached the end of search results."})}catch(t){console.error(t),h(),i.error({position:"topRight",message:"An error occurred while fetching data. Please try again later."})}});O.addEventListener("click",async()=>{c+=1,m.classList.add("is-active-more"),S();try{const s=await p(l,c);L(s.hits),m.classList.remove("is-active-more");const t=Math.ceil(d/15);c<t?v():i.info({position:"topRight",message:"We're sorry, but you've reached the end of search results."});const o=E.firstElementChild.getBoundingClientRect().height;window.scrollBy({top:o*2,behavior:"smooth"})}catch(s){console.error(s),m.classList.remove("is-active-more"),i.error({position:"topRight",message:"Failed to load more images. Please try again."})}});
//# sourceMappingURL=index.js.map
